/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CardsRouteRouteImport } from './routes/cards/route'
import { Route as DataRouteImport } from './routes/data'
import { Route as WhiteboardRouteRouteImport } from './routes/whiteboard/route'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as CardsCardIdRouteImport } from './routes/cards/$cardId'
import { Route as CardsOrphansRouteImport } from './routes/cards/orphans'
import { Route as DemoLocalRouteImport } from './routes/demo/local'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as TestMarkdownRouteImport } from './routes/test/markdown'
import { Route as TestMarkdownInWhiteboardRouteImport } from './routes/test/markdown-in-whiteboard'
import { Route as TestStaticRendererRouteImport } from './routes/test/static-renderer'
import { Route as TestWhiteboardInWhiteboardRouteImport } from './routes/test/whiteboard-in-whiteboard'
import { Route as WhiteboardIndexRouteImport } from './routes/whiteboard/index'
import { Route as WhiteboardWhiteboardIdRouteImport } from './routes/whiteboard/$whiteboardId'
import { Route as TestSubwhiteboardSubwhiteboardidRouteImport } from './routes/test/subwhiteboard/$subwhiteboardid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRouteRoute = CardsRouteRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardRouteRoute = WhiteboardRouteRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRouteRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRouteRoute,
} as any)
const CardsOrphansRoute = CardsOrphansRouteImport.update({
  id: '/orphans',
  path: '/orphans',
  getParentRoute: () => CardsRouteRoute,
} as any)
const DemoLocalRoute = DemoLocalRouteImport.update({
  id: '/demo/local',
  path: '/demo/local',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMarkdownRoute = TestMarkdownRouteImport.update({
  id: '/test/markdown',
  path: '/test/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMarkdownInWhiteboardRoute =
  TestMarkdownInWhiteboardRouteImport.update({
    id: '/test/markdown-in-whiteboard',
    path: '/test/markdown-in-whiteboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestStaticRendererRoute = TestStaticRendererRouteImport.update({
  id: '/test/static-renderer',
  path: '/test/static-renderer',
  getParentRoute: () => rootRouteImport,
} as any)
const TestWhiteboardInWhiteboardRoute =
  TestWhiteboardInWhiteboardRouteImport.update({
    id: '/test/whiteboard-in-whiteboard',
    path: '/test/whiteboard-in-whiteboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const WhiteboardIndexRoute = WhiteboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WhiteboardRouteRoute,
} as any)
const WhiteboardWhiteboardIdRoute = WhiteboardWhiteboardIdRouteImport.update({
  id: '/$whiteboardId',
  path: '/$whiteboardId',
  getParentRoute: () => WhiteboardRouteRoute,
} as any)
const TestSubwhiteboardSubwhiteboardidRoute =
  TestSubwhiteboardSubwhiteboardidRouteImport.update({
    id: '/test/subwhiteboard/$subwhiteboardid',
    path: '/test/subwhiteboard/$subwhiteboardid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRouteRouteWithChildren
  '/whiteboard': typeof WhiteboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/local': typeof DemoLocalRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/test/markdown': typeof TestMarkdownRoute
  '/test/markdown-in-whiteboard': typeof TestMarkdownInWhiteboardRoute
  '/test/static-renderer': typeof TestStaticRendererRoute
  '/test/whiteboard-in-whiteboard': typeof TestWhiteboardInWhiteboardRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/cards/': typeof CardsIndexRoute
  '/test/': typeof TestIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
  '/test/subwhiteboard/$subwhiteboardid': typeof TestSubwhiteboardSubwhiteboardidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/local': typeof DemoLocalRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/test/markdown': typeof TestMarkdownRoute
  '/test/markdown-in-whiteboard': typeof TestMarkdownInWhiteboardRoute
  '/test/static-renderer': typeof TestStaticRendererRoute
  '/test/whiteboard-in-whiteboard': typeof TestWhiteboardInWhiteboardRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/cards': typeof CardsIndexRoute
  '/test': typeof TestIndexRoute
  '/whiteboard': typeof WhiteboardIndexRoute
  '/test/subwhiteboard/$subwhiteboardid': typeof TestSubwhiteboardSubwhiteboardidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRouteRouteWithChildren
  '/whiteboard': typeof WhiteboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/local': typeof DemoLocalRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/test/markdown': typeof TestMarkdownRoute
  '/test/markdown-in-whiteboard': typeof TestMarkdownInWhiteboardRoute
  '/test/static-renderer': typeof TestStaticRendererRoute
  '/test/whiteboard-in-whiteboard': typeof TestWhiteboardInWhiteboardRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/cards/': typeof CardsIndexRoute
  '/test/': typeof TestIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
  '/test/subwhiteboard/$subwhiteboardid': typeof TestSubwhiteboardSubwhiteboardidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/whiteboard'
    | '/about'
    | '/data'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/local'
    | '/demo/tanstack-query'
    | '/test/markdown'
    | '/test/markdown-in-whiteboard'
    | '/test/static-renderer'
    | '/test/whiteboard-in-whiteboard'
    | '/whiteboard/$whiteboardId'
    | '/cards/'
    | '/test/'
    | '/whiteboard/'
    | '/test/subwhiteboard/$subwhiteboardid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/data'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/local'
    | '/demo/tanstack-query'
    | '/test/markdown'
    | '/test/markdown-in-whiteboard'
    | '/test/static-renderer'
    | '/test/whiteboard-in-whiteboard'
    | '/whiteboard/$whiteboardId'
    | '/cards'
    | '/test'
    | '/whiteboard'
    | '/test/subwhiteboard/$subwhiteboardid'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/whiteboard'
    | '/about'
    | '/data'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/local'
    | '/demo/tanstack-query'
    | '/test/markdown'
    | '/test/markdown-in-whiteboard'
    | '/test/static-renderer'
    | '/test/whiteboard-in-whiteboard'
    | '/whiteboard/$whiteboardId'
    | '/cards/'
    | '/test/'
    | '/whiteboard/'
    | '/test/subwhiteboard/$subwhiteboardid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRouteRoute: typeof CardsRouteRouteWithChildren
  WhiteboardRouteRoute: typeof WhiteboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DataRoute: typeof DataRoute
  DemoLocalRoute: typeof DemoLocalRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  TestMarkdownRoute: typeof TestMarkdownRoute
  TestMarkdownInWhiteboardRoute: typeof TestMarkdownInWhiteboardRoute
  TestStaticRendererRoute: typeof TestStaticRendererRoute
  TestWhiteboardInWhiteboardRoute: typeof TestWhiteboardInWhiteboardRoute
  TestIndexRoute: typeof TestIndexRoute
  TestSubwhiteboardSubwhiteboardidRoute: typeof TestSubwhiteboardSubwhiteboardidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRouteRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRouteRoute
    }
    '/cards/orphans': {
      id: '/cards/orphans'
      path: '/orphans'
      fullPath: '/cards/orphans'
      preLoaderRoute: typeof CardsOrphansRouteImport
      parentRoute: typeof CardsRouteRoute
    }
    '/demo/local': {
      id: '/demo/local'
      path: '/demo/local'
      fullPath: '/demo/local'
      preLoaderRoute: typeof DemoLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/markdown': {
      id: '/test/markdown'
      path: '/test/markdown'
      fullPath: '/test/markdown'
      preLoaderRoute: typeof TestMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/markdown-in-whiteboard': {
      id: '/test/markdown-in-whiteboard'
      path: '/test/markdown-in-whiteboard'
      fullPath: '/test/markdown-in-whiteboard'
      preLoaderRoute: typeof TestMarkdownInWhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/static-renderer': {
      id: '/test/static-renderer'
      path: '/test/static-renderer'
      fullPath: '/test/static-renderer'
      preLoaderRoute: typeof TestStaticRendererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/whiteboard-in-whiteboard': {
      id: '/test/whiteboard-in-whiteboard'
      path: '/test/whiteboard-in-whiteboard'
      fullPath: '/test/whiteboard-in-whiteboard'
      preLoaderRoute: typeof TestWhiteboardInWhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard/': {
      id: '/whiteboard/'
      path: '/'
      fullPath: '/whiteboard/'
      preLoaderRoute: typeof WhiteboardIndexRouteImport
      parentRoute: typeof WhiteboardRouteRoute
    }
    '/whiteboard/$whiteboardId': {
      id: '/whiteboard/$whiteboardId'
      path: '/$whiteboardId'
      fullPath: '/whiteboard/$whiteboardId'
      preLoaderRoute: typeof WhiteboardWhiteboardIdRouteImport
      parentRoute: typeof WhiteboardRouteRoute
    }
    '/test/subwhiteboard/$subwhiteboardid': {
      id: '/test/subwhiteboard/$subwhiteboardid'
      path: '/test/subwhiteboard/$subwhiteboardid'
      fullPath: '/test/subwhiteboard/$subwhiteboardid'
      preLoaderRoute: typeof TestSubwhiteboardSubwhiteboardidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CardsRouteRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsOrphansRoute: typeof CardsOrphansRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteRouteChildren: CardsRouteRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
  CardsOrphansRoute: CardsOrphansRoute,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteRouteWithChildren = CardsRouteRoute._addFileChildren(
  CardsRouteRouteChildren,
)

interface WhiteboardRouteRouteChildren {
  WhiteboardWhiteboardIdRoute: typeof WhiteboardWhiteboardIdRoute
  WhiteboardIndexRoute: typeof WhiteboardIndexRoute
}

const WhiteboardRouteRouteChildren: WhiteboardRouteRouteChildren = {
  WhiteboardWhiteboardIdRoute: WhiteboardWhiteboardIdRoute,
  WhiteboardIndexRoute: WhiteboardIndexRoute,
}

const WhiteboardRouteRouteWithChildren = WhiteboardRouteRoute._addFileChildren(
  WhiteboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRouteRoute: CardsRouteRouteWithChildren,
  WhiteboardRouteRoute: WhiteboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DataRoute: DataRoute,
  DemoLocalRoute: DemoLocalRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  TestMarkdownRoute: TestMarkdownRoute,
  TestMarkdownInWhiteboardRoute: TestMarkdownInWhiteboardRoute,
  TestStaticRendererRoute: TestStaticRendererRoute,
  TestWhiteboardInWhiteboardRoute: TestWhiteboardInWhiteboardRoute,
  TestIndexRoute: TestIndexRoute,
  TestSubwhiteboardSubwhiteboardidRoute: TestSubwhiteboardSubwhiteboardidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
