/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CardsRouteRouteImport } from './routes/cards/route'
import { Route as DataRouteImport } from './routes/data'
import { Route as DesktopAuthRouteImport } from './routes/desktop-auth'
import { Route as WhiteboardRouteRouteImport } from './routes/whiteboard/route'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as CardsCardIdRouteImport } from './routes/cards/$cardId'
import { Route as CardsOrphansRouteImport } from './routes/cards/orphans'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as WhiteboardIndexRouteImport } from './routes/whiteboard/index'
import { Route as WhiteboardWhiteboardIdRouteImport } from './routes/whiteboard/$whiteboardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRouteRoute = CardsRouteRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopAuthRoute = DesktopAuthRouteImport.update({
  id: '/desktop-auth',
  path: '/desktop-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardRouteRoute = WhiteboardRouteRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRouteRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRouteRoute,
} as any)
const CardsOrphansRoute = CardsOrphansRouteImport.update({
  id: '/orphans',
  path: '/orphans',
  getParentRoute: () => CardsRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardIndexRoute = WhiteboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WhiteboardRouteRoute,
} as any)
const WhiteboardWhiteboardIdRoute = WhiteboardWhiteboardIdRouteImport.update({
  id: '/$whiteboardId',
  path: '/$whiteboardId',
  getParentRoute: () => WhiteboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRouteRouteWithChildren
  '/whiteboard': typeof WhiteboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/desktop-auth': typeof DesktopAuthRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/cards/': typeof CardsIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/desktop-auth': typeof DesktopAuthRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/cards': typeof CardsIndexRoute
  '/whiteboard': typeof WhiteboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRouteRouteWithChildren
  '/whiteboard': typeof WhiteboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/desktop-auth': typeof DesktopAuthRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/cards/': typeof CardsIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/whiteboard'
    | '/about'
    | '/data'
    | '/desktop-auth'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/tanstack-query'
    | '/whiteboard/$whiteboardId'
    | '/cards/'
    | '/whiteboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/data'
    | '/desktop-auth'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/tanstack-query'
    | '/whiteboard/$whiteboardId'
    | '/cards'
    | '/whiteboard'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/whiteboard'
    | '/about'
    | '/data'
    | '/desktop-auth'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/tanstack-query'
    | '/whiteboard/$whiteboardId'
    | '/cards/'
    | '/whiteboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRouteRoute: typeof CardsRouteRouteWithChildren
  WhiteboardRouteRoute: typeof WhiteboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DataRoute: typeof DataRoute
  DesktopAuthRoute: typeof DesktopAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-auth': {
      id: '/desktop-auth'
      path: '/desktop-auth'
      fullPath: '/desktop-auth'
      preLoaderRoute: typeof DesktopAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRouteRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRouteRoute
    }
    '/cards/orphans': {
      id: '/cards/orphans'
      path: '/orphans'
      fullPath: '/cards/orphans'
      preLoaderRoute: typeof CardsOrphansRouteImport
      parentRoute: typeof CardsRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard/': {
      id: '/whiteboard/'
      path: '/'
      fullPath: '/whiteboard/'
      preLoaderRoute: typeof WhiteboardIndexRouteImport
      parentRoute: typeof WhiteboardRouteRoute
    }
    '/whiteboard/$whiteboardId': {
      id: '/whiteboard/$whiteboardId'
      path: '/$whiteboardId'
      fullPath: '/whiteboard/$whiteboardId'
      preLoaderRoute: typeof WhiteboardWhiteboardIdRouteImport
      parentRoute: typeof WhiteboardRouteRoute
    }
  }
}

interface CardsRouteRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsOrphansRoute: typeof CardsOrphansRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteRouteChildren: CardsRouteRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
  CardsOrphansRoute: CardsOrphansRoute,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteRouteWithChildren = CardsRouteRoute._addFileChildren(
  CardsRouteRouteChildren,
)

interface WhiteboardRouteRouteChildren {
  WhiteboardWhiteboardIdRoute: typeof WhiteboardWhiteboardIdRoute
  WhiteboardIndexRoute: typeof WhiteboardIndexRoute
}

const WhiteboardRouteRouteChildren: WhiteboardRouteRouteChildren = {
  WhiteboardWhiteboardIdRoute: WhiteboardWhiteboardIdRoute,
  WhiteboardIndexRoute: WhiteboardIndexRoute,
}

const WhiteboardRouteRouteWithChildren = WhiteboardRouteRoute._addFileChildren(
  WhiteboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRouteRoute: CardsRouteRouteWithChildren,
  WhiteboardRouteRoute: WhiteboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DataRoute: DataRoute,
  DesktopAuthRoute: DesktopAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
