/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhiteboardIndexRouteImport } from './routes/whiteboard/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as WhiteboardWhiteboardIdRouteImport } from './routes/whiteboard/$whiteboardId'
import { Route as TestWhiteboardInWhiteboardRouteImport } from './routes/test/whiteboard-in-whiteboard'
import { Route as TestMarkdownInWhiteboardRouteImport } from './routes/test/markdown-in-whiteboard'
import { Route as TestMarkdownRouteImport } from './routes/test/markdown'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as CardsOrphansRouteImport } from './routes/cards/orphans'
import { Route as CardsCardIdRouteImport } from './routes/cards/$cardId'
import { Route as TestSubwhiteboardSubwhiteboardidRouteImport } from './routes/test/subwhiteboard/$subwhiteboardid'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardIndexRoute = WhiteboardIndexRouteImport.update({
  id: '/whiteboard/',
  path: '/whiteboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardWhiteboardIdRoute = WhiteboardWhiteboardIdRouteImport.update({
  id: '/whiteboard/$whiteboardId',
  path: '/whiteboard/$whiteboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestWhiteboardInWhiteboardRoute =
  TestWhiteboardInWhiteboardRouteImport.update({
    id: '/test/whiteboard-in-whiteboard',
    path: '/test/whiteboard-in-whiteboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestMarkdownInWhiteboardRoute =
  TestMarkdownInWhiteboardRouteImport.update({
    id: '/test/markdown-in-whiteboard',
    path: '/test/markdown-in-whiteboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestMarkdownRoute = TestMarkdownRouteImport.update({
  id: '/test/markdown',
  path: '/test/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsOrphansRoute = CardsOrphansRouteImport.update({
  id: '/cards/orphans',
  path: '/cards/orphans',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSubwhiteboardSubwhiteboardidRoute =
  TestSubwhiteboardSubwhiteboardidRouteImport.update({
    id: '/test/subwhiteboard/$subwhiteboardid',
    path: '/test/subwhiteboard/$subwhiteboardid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/test/markdown': typeof TestMarkdownRoute
  '/test/markdown-in-whiteboard': typeof TestMarkdownInWhiteboardRoute
  '/test/whiteboard-in-whiteboard': typeof TestWhiteboardInWhiteboardRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/test/': typeof TestIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
  '/test/subwhiteboard/$subwhiteboardid': typeof TestSubwhiteboardSubwhiteboardidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/test/markdown': typeof TestMarkdownRoute
  '/test/markdown-in-whiteboard': typeof TestMarkdownInWhiteboardRoute
  '/test/whiteboard-in-whiteboard': typeof TestWhiteboardInWhiteboardRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/test': typeof TestIndexRoute
  '/whiteboard': typeof WhiteboardIndexRoute
  '/test/subwhiteboard/$subwhiteboardid': typeof TestSubwhiteboardSubwhiteboardidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/orphans': typeof CardsOrphansRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/test/markdown': typeof TestMarkdownRoute
  '/test/markdown-in-whiteboard': typeof TestMarkdownInWhiteboardRoute
  '/test/whiteboard-in-whiteboard': typeof TestWhiteboardInWhiteboardRoute
  '/whiteboard/$whiteboardId': typeof WhiteboardWhiteboardIdRoute
  '/test/': typeof TestIndexRoute
  '/whiteboard/': typeof WhiteboardIndexRoute
  '/test/subwhiteboard/$subwhiteboardid': typeof TestSubwhiteboardSubwhiteboardidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/test/markdown'
    | '/test/markdown-in-whiteboard'
    | '/test/whiteboard-in-whiteboard'
    | '/whiteboard/$whiteboardId'
    | '/test/'
    | '/whiteboard/'
    | '/test/subwhiteboard/$subwhiteboardid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/test/markdown'
    | '/test/markdown-in-whiteboard'
    | '/test/whiteboard-in-whiteboard'
    | '/whiteboard/$whiteboardId'
    | '/test'
    | '/whiteboard'
    | '/test/subwhiteboard/$subwhiteboardid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cards/$cardId'
    | '/cards/orphans'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/test/markdown'
    | '/test/markdown-in-whiteboard'
    | '/test/whiteboard-in-whiteboard'
    | '/whiteboard/$whiteboardId'
    | '/test/'
    | '/whiteboard/'
    | '/test/subwhiteboard/$subwhiteboardid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsOrphansRoute: typeof CardsOrphansRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  TestMarkdownRoute: typeof TestMarkdownRoute
  TestMarkdownInWhiteboardRoute: typeof TestMarkdownInWhiteboardRoute
  TestWhiteboardInWhiteboardRoute: typeof TestWhiteboardInWhiteboardRoute
  WhiteboardWhiteboardIdRoute: typeof WhiteboardWhiteboardIdRoute
  TestIndexRoute: typeof TestIndexRoute
  WhiteboardIndexRoute: typeof WhiteboardIndexRoute
  TestSubwhiteboardSubwhiteboardidRoute: typeof TestSubwhiteboardSubwhiteboardidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard/': {
      id: '/whiteboard/'
      path: '/whiteboard'
      fullPath: '/whiteboard/'
      preLoaderRoute: typeof WhiteboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard/$whiteboardId': {
      id: '/whiteboard/$whiteboardId'
      path: '/whiteboard/$whiteboardId'
      fullPath: '/whiteboard/$whiteboardId'
      preLoaderRoute: typeof WhiteboardWhiteboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/whiteboard-in-whiteboard': {
      id: '/test/whiteboard-in-whiteboard'
      path: '/test/whiteboard-in-whiteboard'
      fullPath: '/test/whiteboard-in-whiteboard'
      preLoaderRoute: typeof TestWhiteboardInWhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/markdown-in-whiteboard': {
      id: '/test/markdown-in-whiteboard'
      path: '/test/markdown-in-whiteboard'
      fullPath: '/test/markdown-in-whiteboard'
      preLoaderRoute: typeof TestMarkdownInWhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/markdown': {
      id: '/test/markdown'
      path: '/test/markdown'
      fullPath: '/test/markdown'
      preLoaderRoute: typeof TestMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/orphans': {
      id: '/cards/orphans'
      path: '/cards/orphans'
      fullPath: '/cards/orphans'
      preLoaderRoute: typeof CardsOrphansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/subwhiteboard/$subwhiteboardid': {
      id: '/test/subwhiteboard/$subwhiteboardid'
      path: '/test/subwhiteboard/$subwhiteboardid'
      fullPath: '/test/subwhiteboard/$subwhiteboardid'
      preLoaderRoute: typeof TestSubwhiteboardSubwhiteboardidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  CardsOrphansRoute: CardsOrphansRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  TestMarkdownRoute: TestMarkdownRoute,
  TestMarkdownInWhiteboardRoute: TestMarkdownInWhiteboardRoute,
  TestWhiteboardInWhiteboardRoute: TestWhiteboardInWhiteboardRoute,
  WhiteboardWhiteboardIdRoute: WhiteboardWhiteboardIdRoute,
  TestIndexRoute: TestIndexRoute,
  WhiteboardIndexRoute: WhiteboardIndexRoute,
  TestSubwhiteboardSubwhiteboardidRoute: TestSubwhiteboardSubwhiteboardidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
